### ISSUE TITLE
python3.x-dev (apt install, x should match your python3 version, ex: 3.8)

### ISSUE THREAD

**Issue by lujl1209** [icon-lab/SynDiff#27]
Could you please provide some instruction on how to install python3.x-dev.
For example, I use python3.10.13, but I cannot find the package with command: sudo yum install python3.10-dev

And I have a problem below:
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
the error information is as below:
Traceback (most recent call last):
  File "/home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/train.py", line 861, in <module>
    init_processes(0, size, train_syndiff, args)
  File "/home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/train.py", line 724, in init_processes
    fn(rank, gpu, args)
  File "/home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/train.py", line 188, in train_syndiff
    from backbones.discriminator import Discriminator_small, Discriminator_large
  File "/home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/backbones/discriminator.py", line 12, in <module>
    from . import up_or_down_sampling
  File "/home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/backbones/up_or_down_sampling.py", line 15, in <module>
    from utils.op import upfirdn2d
  File "/home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/utils/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/utils/op/fused_act.py", line 20, in <module>
    fused = load(
  File "/home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /home/GPU/jllu/software/condaenv/losstorch/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/include -isystem /home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/include/TH -isystem /home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/include/THC -isystem /home/GPU/jllu/software/condaenv/losstorch/include -isystem /home/GPU/jllu/software/condaenv/losstorch/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -std=c++14 -c /home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/utils/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/home/GPU/jllu/software/condaenv/losstorch/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/include -isystem /home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/include/TH -isystem /home/GPU/jllu/software/condaenv/losstorch/lib/python3.10/site-packages/torch/include/THC -isystem /home/GPU/jllu/software/condaenv/losstorch/include -isystem /home/GPU/jllu/software/condaenv/losstorch/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -std=c++14 -c /home/GPU/jllu/work/project/lossless/code/diffusion/SynDiff-main_modified/utils/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
/home/GPU/jllu/software/condaenv/losstorch/gcc/include/c++/shared_mutex: In member function 'bool std::shared_timed_mutex::try_lock_until(const std::chrono::time_point<std::chrono::_V2::system_clock, _Dur2>&)':
/home/GPU/jllu/software/condaenv/losstorch/gcc/include/c++/shared_mutex:419:71: error: taking address of temporary [-fpermissive]
  int __ret = pthread_rwlock_timedwrlock(&_M_rwlock, &__ts);
                                                                       ^
/home/GPU/jllu/software/condaenv/losstorch/gcc/include/c++/shared_mutex: In member function 'bool std::shared_timed_mutex::try_lock_shared_until(const std::chrono::time_point<std::chrono::_V2::system_clock, _Dur2>&)':
/home/GPU/jllu/software/condaenv/losstorch/gcc/include/c++/shared_mutex:472:67: error: taking address of temporary [-fpermissive]
    __ret = pthread_rwlock_timedrdlock(&_M_rwlock, &__ts);
                                                                   ^
ninja: build stopped: subcommand failed.

May I have your suggestion please.
thanks

**Comment by HuiLin0220** [comment]
Did you solve your problem?
